dist: xenial
language: node_js

node_js:
  - 14

git:
  depth: 1

notifications:
  email: false

# Lua package manager, needed to install luacheck (see below).
addons:
  apt:
    packages:
      - luarocks

cache:
  directories:
    - $HOME/.npm

before_script:
  - ( cd tests/travis && npm install )
  - sudo luarocks install luacheck

script:
  # Check JSON assets for syntax errors.
  - ( cd tests/travis && npm test )
  # Check Lua files with "luacheck" tool (Lua static analyzer),
  # but don't fail if the exit code is 1 (which means "there were warnings, but no errors"),
  # only on exit code 2 ("there were errors").
  # There are ~1000 warnings in existing code, so we can't use "no warnings allowed" mode (yet?).
  - luacheck ../../ || [[ $? -le 1 ]]
